#!/usr/bin/env php
<?php

$databasePath = $_SERVER['HOME'] . DIRECTORY_SEPARATOR . '.posty' . DIRECTORY_SEPARATOR;

if (! is_dir($databasePath)) {
    mkdir($databasePath);
}

if(! file_exists($databasePath . 'database.sqlite')) {
    file_put_contents($databasePath . 'database.sqlite', '');
}
